name: CI Checks

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Clone This Repo
        uses: actions/checkout@v2
      - name: Run spellings check
        uses: FreeRTOS/CI-CD-Github-Actions/spellings@main
        with:
          path: ./

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Uncrustify
        run: sudo apt-get install uncrustify
      - name: Run Uncrustify
        run: |
          uncrustify --version
          find Projects Common -iname "*.[hc]" -exec uncrustify --check -c tools/uncrustify.cfg {} +
      - name: Check For Trailing Whitespace
        run: |
          set +e
          grep --exclude="README.md" -rnI -e "[[:blank:]]$" .
          if [ "$?" = "0" ]; then
            echo "Files have trailing whitespace."
            exit 1
          else
            exit 0
          fi

  git-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout awslabs/git-secrets
        uses: actions/checkout@v2
        with:
          repository: awslabs/git-secrets
          ref: master
          path: git-secrets
      - name: Install git-secrets
        run: cd git-secrets && sudo make install && cd ..
      - name: Run git-secrets
        run: |
          git-secrets --register-aws
          git-secrets --scan

  pre-commit-hooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch HEAD revision
        run: git fetch origin
      - name: Install python pip
        run:  sudo apt-get install python3-pip
      - name: Install virtualenv
        run: pip install virtualenv
      - name: create virtual environment
        run: |
          virtualenv venv
          source venv/bin/activate
      - name: install pre-commit package via pip
        run: |
          source venv/bin/activate
          pip install pre-commit
      - name: Run pre-commit hooks
        run: |
          source venv/bin/activate
          if [ -n "${GITHUB_BASE_REF}" ]; then
            BASE_REF="origin/${GITHUB_BASE_REF}"
          elif [ "${GITHUB_REF_NAME}" == "main" ] || [ "${GITHUB_REF_NAME}" == "dev" ]; then
            BASE_REF=""
          else
            BASE_REF="$(git symbolic-ref --short refs/remotes/origin/HEAD)"
          fi
          if [ -n "${BASE_REF}" ]; then
            pre-commit run --from-ref "${BASE_REF}" --to-ref "${GITHUB_SHA}" --show-diff
          else
            pre-commit run --all --show-diff
          fi
